# -*- mode: ruby -*-
# vi: set ft=ruby :
# Used just for encryption module
# VAGRANT_EXPERIMENTAL=disks vagrant up
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
  config.vm.hostname = "ubuntu1"
  config.vm.network "private_network", ip: "192.168.56.101"
  config.vm.disk :disk, size: "1GB", name: "crypt_disk"
  config.vm.disk :disk, size: "500MB", name: "key_disk"
end